<?php
    return [
        //MainController
        '' => [
            'controller'=>'main',
            'action'=>'index',
            ],
        '/' => [
            'controller'=>'main',
            'action'=>'index',
            ],
        'login'=> [
            'controller'=>'main',
            'action'=>'login'
        ],
        'register'=>[
            'controller'=>'main',
            'action'=>'register'
        ],
        'logout'=>[
            'controller'=>'main',
            'action'=>'logout'
        ],
        'forgot'=>[
            'controller'=>'main',
            'action'=>'forgot'
        ],
        'review'=>[
            'controller'=>'main',
            'action'=>'review'
        ],
        'info'=>[
            'controller'=>'main',
            'action'=>'info'
        ],
        //ProductController
        'categories/drinks'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        'categories/drinks/{page:\d+}'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        'categories/deserts'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        'categories/deserts/{page:\d+}'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        'categories/torts'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        'categories/torts/{page:\d+}'=>[
            'controller'=>'product',
            'action'=>'show'
        ],
        //UserController
        'profile'=>[
            'controller'=>'user',
            'action'=>'profile'
        ],
        'settings'=>[
            'controller'=>'user',
            'action'=>'settings'
        ],
        'admin/profile'=>[
            'controller'=>'user',
            'action'=>'profile'
        ],
        'admin/settings'=>[
            'controller'=>'user',
            'action'=>'settings'
        ],
        //AdminController
        'admin/add'=>[
            'controller'=>'admin',
            'action'=>'crud',
        ],
        'admin/edit/{category:\w+}/{id:\d+}'=>[
            'controller'=>'admin',
            'action'=>'crud'
        ],
        'admin/delete/{category:\w+}/{id:\d+}'=>[
            'controller'=>'product',
            'action'=>'delete'
        ],
    ];